2018-05-18 15:02:15,361 [4956] INFO  VpowerUwF4Client.Program - Program Start...
2018-05-18 15:02:15,376 [4956] INFO  VpowerUwF4Client.Program - Log File Check...
2018-05-18 15:02:15,392 [4956] INFO  VpowerUwF4Client.Program - Sno Data Check...
2018-05-18 15:02:15,595 [4956] INFO  VpowerUwF4Client.Program - Transactions sequence updating...
2018-05-18 15:02:15,626 [4956] INFO  VpowerUwF4Client.Program - Transactions sequence is 1
2018-05-18 15:02:15,626 [4956] INFO  VpowerUwF4Client.Program - ServerIp is 0.0.0.0
2018-05-18 15:02:15,626 [4956] INFO  VpowerUwF4Client.Program - ServerPort is 8000
2018-05-18 15:05:02,284 [1276] INFO  CommandServer.ClientManager - Start Receive...
2018-05-18 15:05:02,284 [8076] INFO  VpowerUwF4Client.Program - Client 127.0.0.1:55518 has been Connected. ( 2018-05-18|15:05:02 )
2018-05-18 15:05:02,456 [1276] INFO  VpowerUwF4Client.Program - Client 127.0.0.1:55518 has been Disconnected. ( 2018-05-18|15:05:02 )
2018-05-18 15:07:22,318 [8076] INFO  VpowerUwF4Client.Program - Client 127.0.0.1:55586 has been Connected. ( 2018-05-18|15:07:22 )
2018-05-18 15:07:22,318 [1276] INFO  CommandServer.ClientManager - Start Receive...
2018-05-18 15:07:27,459 [1276] ERROR CommandServer.ClientManager - <Err> at $StartReceive()$ Exception - System.IO.IOException: 転送接続からデータを読み取れません: 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかったため、確立された接続は失敗しました。。 ---> System.Net.Sockets.SocketException: 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかったため、確立された接続は失敗しました。
   場所 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   場所 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- 内部例外スタック トレースの終わり ---
   場所 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   場所 CommandServer.ClientManager.StartReceive(Object sender, DoWorkEventArgs e).
2018-05-18 15:21:27,928 [8408] INFO  VpowerUwF4Client.Program - Program Start...
2018-05-18 15:21:27,944 [8408] INFO  VpowerUwF4Client.Program - Log File Check...
2018-05-18 15:21:27,959 [8408] INFO  VpowerUwF4Client.Program - Sno Data Check...
2018-05-18 15:21:28,178 [8408] INFO  VpowerUwF4Client.Program - Transactions sequence updating...
2018-05-18 15:21:28,194 [8408] INFO  VpowerUwF4Client.Program - Transactions sequence is 1
2018-05-18 15:21:28,209 [8408] INFO  VpowerUwF4Client.Program - ServerIp is 0.0.0.0
2018-05-18 15:21:28,209 [8408] INFO  VpowerUwF4Client.Program - ServerPort is 8000
2018-05-18 15:23:49,401 [6676] INFO  CommandServer.ClientManager - Start Receive...
2018-05-18 15:23:49,401 [7988] INFO  VpowerUwF4Client.Program - Client 127.0.0.1:58026 has been Connected. ( 2018-05-18|15:23:49 )
2018-05-18 15:23:54,558 [6676] ERROR CommandServer.ClientManager - <Err> at $StartReceive()$ Exception - System.IO.IOException: 転送接続からデータを読み取れません: 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかったため、確立された接続は失敗しました。。 ---> System.Net.Sockets.SocketException: 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかったため、確立された接続は失敗しました。
   場所 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   場所 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- 内部例外スタック トレースの終わり ---
   場所 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   場所 CommandServer.ClientManager.StartReceive(Object sender, DoWorkEventArgs e).
2018-05-18 15:26:27,770 [7988] INFO  VpowerUwF4Client.Program - Client 127.0.0.1:58197 has been Connected. ( 2018-05-18|15:26:27 )
2018-05-18 15:26:27,770 [8336] INFO  CommandServer.ClientManager - Start Receive...
2018-05-18 15:26:32,864 [8336] ERROR CommandServer.ClientManager - <Err> at $StartReceive()$ Exception - System.IO.IOException: 転送接続からデータを読み取れません: 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかったため、確立された接続は失敗しました。。 ---> System.Net.Sockets.SocketException: 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかったため、確立された接続は失敗しました。
   場所 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   場所 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- 内部例外スタック トレースの終わり ---
   場所 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   場所 CommandServer.ClientManager.StartReceive(Object sender, DoWorkEventArgs e).
2018-05-18 15:37:37,571 [7988] INFO  VpowerUwF4Client.Program - Client 127.0.0.1:58746 has been Connected. ( 2018-05-18|15:37:37 )
2018-05-18 15:37:37,571 [8336] INFO  CommandServer.ClientManager - Start Receive...
2018-05-18 15:37:37,696 [8336] ERROR CommandServer.ClientManager - <Err> at $StartReceive()$ check sum is incorrect.
2018-05-18 15:37:37,727 [8336] INFO  VpowerUwF4Client.Program - Client 127.0.0.1:58746 has been Disconnected. ( 2018-05-18|15:37:37 )
